"""fix cvss v40 sub impact column types

Revision ID: 060109388938
Revises: 5835a7b4641f
Create Date: 2026-07-03 20:52:03.128472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '060109388938'
down_revision: Union[str, Sequence[str], None] = '5835a7b4641f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cvss_data_v40', 'sub_confidentiality_impact',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=50),
               existing_nullable=True,
               schema='vulnradar')
    op.alter_column('cvss_data_v40', 'sub_integrity_impact',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=50),
               existing_nullable=True,
               schema='vulnradar')
    op.alter_column('cvss_data_v40', 'sub_availability_impact',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=50),
               existing_nullable=True,
               schema='vulnradar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cvss_data_v40', 'sub_availability_impact',
               existing_type=sa.String(length=50),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True,
               schema='vulnradar')
    op.alter_column('cvss_data_v40', 'sub_integrity_impact',
               existing_type=sa.String(length=50),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True,
               schema='vulnradar')
    op.alter_column('cvss_data_v40', 'sub_confidentiality_impact',
               existing_type=sa.String(length=50),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True,
               schema='vulnradar')
    # ### end Alembic commands ###
