"""fix cvss v4 impact column types

Revision ID: 18f637b90c41
Revises: 20260703_add_cvss_v40_sub_scores
Create Date: 2026-07-03 20:18:40.908555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18f637b90c41'
down_revision: Union[str, Sequence[str], None] = '20260703_add_cvss_v40_sub_scores'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cvss_data_v31', ['metric_id'], schema='vulnradar')
    op.create_unique_constraint(None, 'cvss_data_v40', ['metric_id'], schema='vulnradar')
    op.alter_column('github_advisories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True,
               schema='vulnradar')
    op.drop_index(op.f('ix_github_advisories_cve_db_id'), table_name='github_advisories', schema='vulnradar')
    op.drop_index(op.f('ix_github_advisories_cve_id'), table_name='github_advisories', schema='vulnradar')
    op.drop_index(op.f('ix_github_advisories_severity'), table_name='github_advisories', schema='vulnradar')
    op.create_index(op.f('ix_vulnradar_github_advisories_cve_id'), 'github_advisories', ['cve_id'], unique=False, schema='vulnradar')
    op.alter_column('github_advisory_references', 'source',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               existing_nullable=True,
               schema='vulnradar')
    op.alter_column('osv_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True,
               schema='vulnradar')
    op.drop_index(op.f('ix_osv_records_cve_db_id'), table_name='osv_records', schema='vulnradar')
    op.drop_index(op.f('ix_osv_records_cve_id'), table_name='osv_records', schema='vulnradar')
    op.create_index(op.f('ix_vulnradar_osv_records_cve_id'), 'osv_records', ['cve_id'], unique=False, schema='vulnradar')
    op.drop_constraint(op.f('sync_runs_sync_state_id_fkey'), 'sync_runs', schema='vulnradar', type_='foreignkey')
    op.create_foreign_key(None, 'sync_runs', 'sync_state', ['sync_state_id'], ['id'], source_schema='vulnradar', referent_schema='vulnradar')
    op.alter_column('vendor_advisories', 'is_available',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True,
               schema='vulnradar')
    op.alter_column('vendor_advisories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True,
               schema='vulnradar')
    op.drop_index(op.f('ix_vendor_advisories_cve_db_id'), table_name='vendor_advisories', schema='vulnradar')
    op.drop_index(op.f('ix_vendor_advisories_cve_id'), table_name='vendor_advisories', schema='vulnradar')
    op.drop_index(op.f('ix_vendor_advisories_vendor'), table_name='vendor_advisories', schema='vulnradar')
    op.create_index(op.f('ix_vulnradar_vendor_advisories_cve_id'), 'vendor_advisories', ['cve_id'], unique=False, schema='vulnradar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnradar_vendor_advisories_cve_id'), table_name='vendor_advisories', schema='vulnradar')
    op.create_index(op.f('ix_vendor_advisories_vendor'), 'vendor_advisories', ['vendor'], unique=False, schema='vulnradar')
    op.create_index(op.f('ix_vendor_advisories_cve_id'), 'vendor_advisories', ['cve_id'], unique=False, schema='vulnradar')
    op.create_index(op.f('ix_vendor_advisories_cve_db_id'), 'vendor_advisories', ['cve_db_id'], unique=False, schema='vulnradar')
    op.alter_column('vendor_advisories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True,
               schema='vulnradar')
    op.alter_column('vendor_advisories', 'is_available',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True,
               schema='vulnradar')
    op.drop_constraint(None, 'sync_runs', schema='vulnradar', type_='foreignkey')
    op.create_foreign_key(op.f('sync_runs_sync_state_id_fkey'), 'sync_runs', 'sync_state', ['sync_state_id'], ['id'], source_schema='vulnradar', referent_schema='vulnradar', ondelete='CASCADE')
    op.drop_index(op.f('ix_vulnradar_osv_records_cve_id'), table_name='osv_records', schema='vulnradar')
    op.create_index(op.f('ix_osv_records_cve_id'), 'osv_records', ['cve_id'], unique=False, schema='vulnradar')
    op.create_index(op.f('ix_osv_records_cve_db_id'), 'osv_records', ['cve_db_id'], unique=False, schema='vulnradar')
    op.alter_column('osv_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True,
               schema='vulnradar')
    op.alter_column('github_advisory_references', 'source',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text("'GitHub Advisory'::character varying"),
               existing_nullable=True,
               schema='vulnradar')
    op.drop_index(op.f('ix_vulnradar_github_advisories_cve_id'), table_name='github_advisories', schema='vulnradar')
    op.create_index(op.f('ix_github_advisories_severity'), 'github_advisories', ['severity'], unique=False, schema='vulnradar')
    op.create_index(op.f('ix_github_advisories_cve_id'), 'github_advisories', ['cve_id'], unique=False, schema='vulnradar')
    op.create_index(op.f('ix_github_advisories_cve_db_id'), 'github_advisories', ['cve_db_id'], unique=False, schema='vulnradar')
    op.alter_column('github_advisories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True,
               schema='vulnradar')
    op.drop_constraint(None, 'cvss_data_v40', schema='vulnradar', type_='unique')
    op.drop_constraint(None, 'cvss_data_v31', schema='vulnradar', type_='unique')
    # ### end Alembic commands ###
