"""create cves table

Revision ID: 33576323b96b
Revises: 822c1bc277d8
Create Date: 2026-06-14 21:41:45.543979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33576323b96b'
down_revision: Union[str, Sequence[str], None] = '822c1bc277d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exploit_references',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cve_db_id', sa.BigInteger(), nullable=False),
    sa.Column('cve_id', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('exploit_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('module', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['cve_db_id'], ['vulnradar.cves.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='vulnradar'
    )
    op.create_index(op.f('ix_vulnradar_exploit_references_cve_id'), 'exploit_references', ['cve_id'], unique=False, schema='vulnradar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnradar_exploit_references_cve_id'), table_name='exploit_references', schema='vulnradar')
    op.drop_table('exploit_references', schema='vulnradar')
    # ### end Alembic commands ###
