"""add new tables

Revision ID: 822c1bc277d8
Revises: 9d7b8a4c2f10
Create Date: 2026-06-14 16:17:34.476788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '822c1bc277d8'
down_revision: Union[str, Sequence[str], None] = '9d7b8a4c2f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epss',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cve_db_id', sa.BigInteger(), nullable=False),
    sa.Column('cve_id', sa.String(length=50), nullable=False),
    sa.Column('epss_score', sa.DECIMAL(precision=10, scale=5), nullable=True),
    sa.Column('percentile', sa.DECIMAL(precision=10, scale=5), nullable=True),
    sa.ForeignKeyConstraint(['cve_db_id'], ['vulnradar.cves.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='vulnradar'
    )
    op.create_index(op.f('ix_vulnradar_epss_cve_id'), 'epss', ['cve_id'], unique=False, schema='vulnradar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnradar_epss_cve_id'), table_name='epss', schema='vulnradar')
    op.drop_table('epss', schema='vulnradar')
    # ### end Alembic commands ###
