"""Create users projects project_items tables

Revision ID: c331ef333319
Revises: 7e4aeea150ff
Create Date: 2026-06-18 16:54:45.092235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c331ef333319'
down_revision: Union[str, Sequence[str], None] = '7e4aeea150ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='vulnradar'
    )
    op.create_index(op.f('ix_vulnradar_users_email'), 'users', ['email'], unique=True, schema='vulnradar')
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['vulnradar.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='vulnradar'
    )
    op.create_table('project_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('cve_id', sa.String(length=50), nullable=False),
    sa.Column('cve_db_id', sa.BigInteger(), nullable=True),
    sa.Column('criticality', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cve_db_id'], ['vulnradar.cves.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['vulnradar.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='vulnradar'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_items', schema='vulnradar')
    op.drop_table('projects', schema='vulnradar')
    op.drop_index(op.f('ix_vulnradar_users_email'), table_name='users', schema='vulnradar')
    op.drop_table('users', schema='vulnradar')
    # ### end Alembic commands ###
